version: '1'
services:
  minecraft-server:
    image: debian:latest
    volumes:
      - ./minecraft:/minecraft
      - ./scripts:/home/scripts
    ports:
      - 25565:25565
    working_dir: /home/scripts
    entrypoint: ["bash", "setup.sh"]
    restart: unless-stopped