version: '1'
services:
  minecraft-server:
    image: alpine:latest
    volumes:
      - ./minecraft:/minecraft
      - ./scripts:/home/scripts
    ports:
      - 25565:25565
    working_dir: /home/scripts
    entrypoint: ["sh", "setup.sh"]
    restart: unless-stopped

# version: '1'
# services:
#   minecraft-server:
#     image: ubuntu:latest
#     volumes:
#       - ./minecraft:/minecraft
#       - ./scripts:/home/scripts
#     ports:
#       - 25565:25565
#     working_dir: /home/scripts
#     entrypoint: ["sh", "setup.sh"]
#     restart: unless-stopped